name: InventoryFlow
options:
  bundleIdPrefix: com.inventoryflow.app
  deploymentTarget:
    iOS: 17.0
    macOS: 14.0
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    majorVersion: 6.0.0

targets:
  InventoryFlow_iOS:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Sources/Shared
      - path: Sources/iOS
    settings:
      base:
        PRODUCT_NAME: InventoryFlow
        SWIFT_VERSION: 5.9
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    dependencies:
      - sdk: SwiftUI.framework
      - package: GRDB

  InventoryFlow_macOS:
    type: application
    platform: macOS
    deploymentTarget: 14.0
    sources:
      - path: Sources/Shared
      - path: Sources/macOS
    settings:
      base:
        PRODUCT_NAME: InventoryFlow
        SWIFT_VERSION: 5.9
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: InventoryFlow
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    dependencies:
      - sdk: SwiftUI.framework
      - package: GRDB
